<a href="https://colab.research.google.com/github/divyachaudhary06/UCS420/blob/main/ASSIGNMENT_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
ASSIGNEMNT-6

ASSIGNMENT-6  
                        NAME-DIVYA CHAUDHARY.                                                                          

 ROLL NO-1024160083

GROUP-3P13

QUESTION-1

In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

# a. Add 2°C to every reading using vectorization
corrected_temperature = temperature + 2
print("a. Corrected temperatures:", corrected_temperature)

# b. Convert Celsius to Fahrenheit
fahrenheit = (9/5) * corrected_temperature + 32
print("b. Fahrenheit:", fahrenheit)

# c. Identify readings greater than 32°C
greater_than_32 = corrected_temperature[corrected_temperature > 32]
print("c. Readings greater than 32°C:", greater_than_32)

# d. Count how many readings exceed 32°C
count = np.sum(corrected_temperature > 32)
print("d. Number of readings exceeding 32°C:", count)

# e. Explanation
print("""
e. Vectorization performs operations on the entire NumPy array at once,
without explicitly using a for loop. Boolean indexing allows us to
select elements satisfying a condition. These operations are faster,
simpler, and more efficient for processing large datasets.
""")

a. Corrected temperatures: [27 30 33 37 40 29 35 42]
b. Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
c. Readings greater than 32°C: [33 37 40 35 42]
d. Number of readings exceeding 32°C: 5

e. Vectorization performs operations on the entire NumPy array at once,
without explicitly using a for loop. Boolean indexing allows us to
select elements satisfying a condition. These operations are faster,
simpler, and more efficient for processing large datasets.



In [2]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

# a. Calculate total steps
print("a. Total steps:", np.sum(steps))

# b. Calculate mean number of steps
print("b. Mean steps:", np.mean(steps))

# c. Maximum and minimum values
print("c. Maximum:", np.max(steps))
print("   Minimum:", np.min(steps))

# d. Total steps for each day (axis=0)
print("d. Total steps for each day:", np.sum(steps, axis=0))

# e. Total steps for each user (axis=1)
print("e. Total steps for each user:", np.sum(steps, axis=1))

# f. Position containing maximum number of steps
max_position = np.unravel_index(np.argmax(steps), steps.shape)
print("f. Maximum value:", np.max(steps))
print("   Position (row, column):", max_position)

a. Total steps: 84200
b. Mean steps: 7016.666666666667
c. Maximum: 9500
   Minimum: 4500
d. Total steps for each day: [26500 27300 30400]
e. Total steps for each user: [18300 24500 14400 27000]
f. Maximum value: 9500
   Position (row, column): (np.int64(3), np.int64(2))


In [3]:
import numpy as np

# a. Create original array
original = np.array([1, 2, 3, 4, 5, 6])
print("a. Original:", original)

# b. Slice index 1 to 4
subset = original[1:5]
print("b. Subset:", subset)

# c. Modify first element of subset
subset[0] = 999

print("c. Original after modifying subset:", original)
print("   Subset:", subset)

# d. Create another slice using copy()
copied = original[1:5].copy()

copied[0] = 500

print("d. Original after modifying copied array:", original)
print("   Copied array:", copied)

# e. Create numbers 1 to 12 and reshape into 3 x 4
matrix = np.arange(1, 13).reshape(3, 4)

print("e. 3 x 4 Matrix:")
print(matrix)

# f. Indexing and slicing

# First row
print("f. First row:", matrix[0])

# Last row
print("   Last row:", matrix[-1])

# Second column
print("   Second column:", matrix[:, 1])

# Rows 1-2 and columns 2-3
print("   Rows 1-2 and columns 2-3:")
print(matrix[1:3, 2:4])

# g. Flatten using flatten() and ravel()
flattened = matrix.flatten()
raveled = matrix.ravel()

print("g. Flatten:", flattened)
print("   Ravel:", raveled)

# h. Modify ravel()
raveled[0] = 100

print("h. Matrix after modifying ravel:")
print(matrix)
print("   Raveled array:", raveled)

# i. Modify flatten()
flattened[1] = 200

print("i. Matrix after modifying flatten:")
print(matrix)
print("   Flattened array:", flattened)

# j. Shape, dimensions, size and datatype
print("j. Shape:", matrix.shape)
print("   Dimensions:", matrix.ndim)
print("   Size:", matrix.size)
print("   Data type:", matrix.dtype)

a. Original: [1 2 3 4 5 6]
b. Subset: [2 3 4 5]
c. Original after modifying subset: [  1 999   3   4   5   6]
   Subset: [999   3   4   5]
d. Original after modifying copied array: [  1 999   3   4   5   6]
   Copied array: [500   3   4   5]
e. 3 x 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
f. First row: [1 2 3 4]
   Last row: [ 9 10 11 12]
   Second column: [ 2  6 10]
   Rows 1-2 and columns 2-3:
[[ 7  8]
 [11 12]]
g. Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
   Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
h. Matrix after modifying ravel:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
   Raveled array: [100   2   3   4   5   6   7   8   9  10  11  12]
i. Matrix after modifying flatten:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
   Flattened array: [  1 200   3   4   5   6   7   8   9  10  11  12]
j. Shape: (3, 4)
   Dimensions: 2
   Size: 12
   Data type: int64


In [4]:
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

# a. Shape and dimensions
print("a. Shape of X:", X.shape)
print("   Dimensions of X:", X.ndim)

# b. Transpose
print("b. X transpose:")
print(X.T)

# c. Matrix product X.T @ X
XT_X = X.T @ X

print("c. X.T @ X:")
print(XT_X)

# d. Matrix inverse
inverse = np.linalg.inv(XT_X)

print("d. Inverse of X.T @ X:")
print(inverse)

# e. Ordinary Least Squares
beta = inverse @ X.T @ y

print("e. Coefficients (beta):")
print(beta)

# f. Explanation
print("""
f. The coefficients represent the contribution of each feature
to the predicted assistance score.

Beta[0] -> Sleep hours coefficient
Beta[1] -> Activity level coefficient
Beta[2] -> Stress level coefficient
""")

# g. Predict assistance score for a new user
new_user = np.array([5, 40, 7])

prediction = new_user @ beta

print("g. Predicted assistance score:", prediction)

a. Shape of X: (4, 3)
   Dimensions of X: 2
b. X transpose:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
c. X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
d. Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
e. Coefficients (beta):
[-0.15921454  0.14083853 10.06302242]

f. The coefficients represent the contribution of each feature
to the predicted assistance score.

Beta[0] -> Sleep hours coefficient
Beta[1] -> Activity level coefficient
Beta[2] -> Stress level coefficient

g. Predicted assistance score: 75.27862544779117
