<a href="https://colab.research.google.com/github/divyachaudhary06/UCS420/blob/main/ASSIGNMENT_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ASSIGNMENT-5

NAME- DIVYA CHAUDARY.    
ROLL NO-1024160083.    
GROUP-3P13

QUESTION -1

In [1]:
import numpy as np


In [12]:
a=np.array([1,2,3,4,5])

In [13]:
## A)
a=a+2
print(a)

[3 4 5 6 7]


In [14]:
## b)
a=a*3
print(a)

[ 9 12 15 18 21]


In [15]:
##C)
a=a/2
print(a)

[ 4.5  6.   7.5  9.  10.5]


QUESTION-2

In [17]:
arr=np.array([1,2,3,4,5,6])

In [19]:
#A)
arr=arr[::-1]
print(arr)

[6 5 4 3 2 1]


In [25]:
#b)
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])

values, counts = np.unique(x, return_counts=True)
most_freq = values[np.argmax(counts)]

indices = np.where(x == most_freq)[0]

print("Most frequent value for x:", most_freq)
print("Indices for x:", indices)

values, counts = np.unique(y, return_counts=True)
most_freq = values[np.argmax(counts)]

indices = np.where(y == most_freq)[0]

print("\nMost frequent value for y:", most_freq)
print("Indices for y:", indices)

Most frequent value for x: 1
Indices for x: [0 5 7 8 9]

Most frequent value for y: 1
Indices for y: [0 1 2]


QUESTION-3

In [30]:
p=np.array([[10,20,30],[40,50,60],[70,80,90]])

print(p[0,1])
print(p[2,0])

20
70


QUESTION-4

In [53]:
divya=np.linspace(10,100,num=25)

#a)
print(divya.ndim)
#b)
print(divya.shape)
#c)
print(divya.size)
#d)
print(divya.dtype)
#e)
print(divya.nbytes)
#f)

#G)
print(divya.T)

1
(25,)
25
float64
200
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


QUESTION-5

In [60]:
UCS420_divya=np.array([10,20,30,40,
                      50,60,70,80,
                      90,15,20,35])
UCS420_divya.reshape(3,4)
print("mean:",np.mean(UCS420_divya))
print("median:",np.median(UCS420_divya))
print("min:",np.min(UCS420_divya))
print("max:",np.max(UCS420_divya))
print("unique:",np.unique(UCS420_divya))

mean: 43.333333333333336
median: 37.5
min: 10
max: 90
unique: [10 15 20 30 35 40 50 60 70 80 90]


In [63]:
reshaped_ucs420_divya=UCS420_divya.reshape(4,3)
resized_ucs420_divya=np.resize(UCS420_divya,(2,3))
print(reshaped_ucs420_divya)
print(resized_ucs420_divya)


[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
